#
# Copyright 2014 Freescale Semiconductor, Inc.
#
# SPDX-License-Identifier:      GPL-2.0+
#

obj-y += ge110pro.o ns_access.o ls102xa_stream_id.o 
obj-$(CONFIG_DEEP_SLEEP) += arm_sleep.o
obj-$(CONFIG_ARMV7_PSCI) += psci.o
